### ISSUE TITLE
can you add documentation on how to add eslint and jscs as well?

### ISSUE THREAD

**Issue by crisryantan** [dwyl/learn-pre-commit#3]
can you add documentation on how to add eslint and jscs as well?

**Comment by crisryantan** [comment]
found out a way to test all of them in one go. In my gulp configuration I chained all the necessary tests and added an npm script "test" : "gulp test" which will do everything. :D

**Comment by nelsonic** [comment]
Ah, gulp task... ok. fair enough. provided you are (_explicitly_) adding gulp to your [**devDependencies**](https://github.com/npm/npm/blob/2e3776bf5676bc24fec6239a3420f377fe98acde/doc/files/package.json.md#devdependencies) so the users of your module know they need to have it installed. :+1: 
Does Gulp also run your Unit/Functional/End-to-End tests?

**Comment by crisryantan** [comment]
It runs my unit and functional tests. Haven't done it with end-to-end tests yet.

**Comment by nelsonic** [comment]
Cool. sounds like you've got a good solution to your probrem. :+1:

**Comment by crisryantan** [comment]
Thanks man. So I separated my linting tests and unit/functional tests. I integrated the commit-hooks with my linting tests. Unit/functional tests on Circle CI/Travis/etc.

gulpfile.js

```
gulp.task( 'vet', [ 'eslint' ], function () {
    log( 'Analyzing source with JSHint and JSCS' );
    return gulp
        .src( config.alljs )
        .pipe( $.if( args.verbose, $.print() ) )
        .pipe( $.jshint() )
        .pipe( $.jshint.reporter( 'jshint-stylish', { 'verbose' : true } ) )
        .pipe( $.jshint.reporter( 'fail' ) )
        .pipe( $.jscs() );
} );

gulp.task( 'eslint', function () {
    log( 'Analyzing source with ESLint' );
    return gulp
        .src( config.alljs )
        .pipe( $.eslint() )
        .pipe( $.eslint.format() );
} );
```

package.json

```
 "scripts": {
    "lint": "npm run gulp -- vet"
},
"pre-commit": [
    "lint"
],
```

**Comment by crisryantan** [comment]
I could add a pull-request to add this into the documentation if you'd like.

**Comment by nelsonic** [comment]
We are trying to avoid Gulp/Grunt/etc these days ...
See: 
- http://blog.keithcirkel.co.uk/why-we-should-stop-using-grunt/
- http://blog.keithcirkel.co.uk/how-to-use-npm-as-a-build-tool

Not that those tools aren't _good_, they just add complexity to our process where we need it to be as _simple as possible_ for beginners to be able to understand our projects.

**Comment by crisryantan** [comment]
Okay, I understand if that is the case. We would need documentation for the people who want to add eslint and jscs as commit hooks without using gulp or grunt.
